"""Mabel's domain layer.

Pure by contract: no I/O, no DB, no network, no clock reads hidden inside a
model. Everything here is a value you can construct in a test in one line,
which is why it carries the invariants that matter — money is integer cents,
phone numbers are normalised E.164, `never_say` always contains `price`, and
after-hours is computed from an IANA zone rather than stored.

If you find yourself wanting to import a database session in this package,
the code you are writing belongs in `packages/db/` instead.
"""

from __future__ import annotations

from mabel_domain.enums import (
    AppointmentStatus,
    CallOutcome,
    Direction,
    EventKind,
    IntegrationProvider,
    IntegrationStatus,
    LeadStatus,
    NeverSay,
    NotificationChannel,
    NotificationKind,
    NotificationStatus,
    Plan,
    QaFlag,
    Severity,
    TenantStatus,
    Trade,
    Urgency,
    UserRole,
)
from mabel_domain.hours import in_quiet_hours, is_after_hours, is_open, to_tenant_local
from mabel_domain.models import (
    AgentConfig,
    Appointment,
    AuditEntry,
    BusinessHours,
    Call,
    CommunicationEvent,
    Contact,
    DayHours,
    Integration,
    IntegrationEvent,
    KnowledgeItem,
    Lead,
    Location,
    MonthlyReport,
    Notification,
    OncallSchedule,
    OncallShift,
    QueuedJob,
    SmsSession,
    Subscription,
    Tenant,
    Transcript,
    TranscriptTurn,
    UsageDay,
    User,
    VerticalRuleset,
)
from mabel_domain.money import (
    Money,
    MoneyError,
    cents_from_decimal,
    parse_owner_amount,
    sum_cents,
)
from mabel_domain.phone import (
    E164,
    PhoneError,
    format_national,
    last_ten,
    normalize_e164,
    try_normalize_e164,
)

__all__ = [
    "E164",
    "AgentConfig",
    "Appointment",
    "AppointmentStatus",
    "AuditEntry",
    "BusinessHours",
    "Call",
    "CallOutcome",
    "CommunicationEvent",
    "Contact",
    "DayHours",
    "Direction",
    "EventKind",
    "Integration",
    "IntegrationEvent",
    "IntegrationProvider",
    "IntegrationStatus",
    "KnowledgeItem",
    "Lead",
    "LeadStatus",
    "Location",
    "Money",
    "MoneyError",
    "MonthlyReport",
    "NeverSay",
    "Notification",
    "NotificationChannel",
    "NotificationKind",
    "NotificationStatus",
    "OncallSchedule",
    "OncallShift",
    "PhoneError",
    "Plan",
    "QaFlag",
    "QueuedJob",
    "Severity",
    "SmsSession",
    "Subscription",
    "Tenant",
    "TenantStatus",
    "Trade",
    "Transcript",
    "TranscriptTurn",
    "Urgency",
    "UsageDay",
    "User",
    "UserRole",
    "VerticalRuleset",
    "cents_from_decimal",
    "format_national",
    "in_quiet_hours",
    "is_after_hours",
    "is_open",
    "last_ten",
    "normalize_e164",
    "parse_owner_amount",
    "sum_cents",
    "to_tenant_local",
    "try_normalize_e164",
]
