"""Alembic environment.

Two things worth knowing before you touch this file.

**Migrations run as `mabel_admin`, not `mabel_app`.** `mabel_admin` holds
BYPASSRLS and owns the tables; `mabel_app` is what the application connects as
and has RLS forced on it. Running a migration as the app role would either
fail on the DDL or, worse, succeed and leave the new table owned by the role
that is supposed to be constrained by it.

**Agents draft migrations. Sam runs them.** `alembic upgrade head --sql` is the
dry run CI does. Nothing in this repo calls `upgrade()` against a live
database, and nothing should.

There is no `target_metadata`: the schema is authored by hand from
01-SCHEMA.sql rather than autogenerated. Autogenerate does not know about RLS
policies, partial indexes with `WHERE` clauses, role grants, or `pg_cron`
entries, and silently dropping any of those is a cross-tenant leak.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None


def _url() -> str:
    """Prefer MIGRATION_DATABASE_URL (the `mabel_admin` connection) and fall
    back to DATABASE_URL only for an offline `--sql` render, which connects to
    nothing."""
    url = os.environ.get("MIGRATION_DATABASE_URL") or os.environ.get("DATABASE_URL")
    if not url:
        if context.is_offline_mode():
            # `--sql` renders DDL without a connection. A placeholder here is
            # not a credential; it never leaves the process and never dials
            # anything. Everything else fails closed.
            return "postgresql://offline/render-only"
        raise RuntimeError(
            "MIGRATION_DATABASE_URL is unset. Migrations connect as mabel_admin. "
            "See docs/BLOCKED.md #1."
        )
    # asyncpg is the app driver; migrations run synchronously on psycopg.
    return url.replace("postgresql+asyncpg://", "postgresql://", 1)


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = _url()
    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
